name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build (Gradle)
        run: ./gradlew clean bootJar -x test

      - name: List build artifacts
        run: ls -la build/libs/

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: build/libs/*.jar
          target: /home/ec2-user/app/
          strip_components: 2

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e

            # 디렉토리 준비
            mkdir -p /home/ec2-user/app
            chown ec2-user:ec2-user /home/ec2-user/app

            # 업로드된 JAR 파일 확인
            echo "=== 업로드된 파일 목록 ==="
            ls -la /home/ec2-user/app/

            # 최신 JAR를 app.jar로 복사
            LATEST_JAR=$(ls -t /home/ec2-user/app/*.jar | head -n1)
            if [ -n "$LATEST_JAR" ]; then
              echo "최신 JAR 파일: $LATEST_JAR"
              cp "$LATEST_JAR" /home/ec2-user/app/app.jar
              chown ec2-user:ec2-user /home/ec2-user/app/app.jar
              echo "app.jar로 복사 완료"
            else
              echo "ERROR: JAR 파일을 찾을 수 없습니다!"
              exit 1
            fi

            echo "=== 최종 파일 목록 ==="
            ls -la /home/ec2-user/app/
  
            # GitHub Secrets에서 환경변수 파일 생성
            sudo bash -c 'cat > /etc/myapp.env <<EOF
            ALADIN_API_TTB_KEY=${{ secrets.ALADIN_API_TTB_KEY }}
            CORS_ALLOWED_ORIGINS=${{ secrets.CORS_ALLOWED_ORIGINS }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_URL=${{ secrets.DB_URL }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            JWT_ACCESS_TOKEN_EXPIRATION=${{ secrets.JWT_ACCESS_EXPIRATION }}
            JWT_REFRESH_TOKEN_EXPIRATION=${{ secrets.JWT_REFRESH_EXPIRATION }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}
            KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}
            KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }}
            SERVER_PORT=${{ secrets.SERVER_PORT }}
            EOF'

            sudo chown root:root /etc/myapp.env
            sudo chmod 600 /etc/myapp.env
            
            # systemd 재로드 및 재시작
            sudo systemctl daemon-reload
            sudo systemctl restart myapp
            sudo systemctl status myapp --no-pager
